# -*- coding: utf-8 -*-
"""SJC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t3We9qwhdMrYZPJD79m1Ao_3ltEo9l2s

## Import Libraries
"""

import requests
import pandas as pd
import numpy as np
import csv
import matplotlib.pyplot as plt
import re

"""## Load CSV"""

df = pd.read_csv ('https://data.sanjoseca.gov/dataset/c5929f1b-7dbe-445e-83ed-35cca0d3ca8b/resource/9ca4f4d5-2a86-4a26-9a63-5956e68571f2/download/policecalls2021.csv')

"""## Explore Data"""

## Retrieve top records

print(df.head(5))

## Read column headers
df.columns

## Read each record for a specified column(s)
print(df[['EID', 'CALL_TYPE', 'ADDRESS']])

## Iterate through each row
for index, row in df.iterrows():
  print(index, row['ADDRESS'])

"""###Filtering & Sorting Data"""

## Filter by date and call type 

df.loc[(df['OFFENSE_DATE'] == "1/1/2021 12:00:00 AM") & (df['CALL_TYPE'] == 'DISTURBANCE')]

## Filter by time

df.loc[(df['OFFENSE_TIME'] > "21:00:00")]

## Filter by string containing declared characters

df.loc[df['ADDRESS'].str.contains('Delta', flags=re.I, na=False)]

# df.loc[df['ADDRESS'].str.contains('Berryessa|Delta', flags=re.I, na=False)]

# df.loc[df['ADDRESS'].str.contains('B[a-z]*', flags=re.I, regex=True,na=False)]

## Sort Data

df.sort_values(['PRIORITY','REPORT_DATE', 'OFFENSE_TIME'], ascending=[1,1,1])

## Use Group By Function to minimize DataFrame

df['count'] = 1

new_df = df.groupby(['CALL_TYPE','REPORT_DATE']).count()['count']

new_df

new_df

"""## Saving CSV"""

new_df.to_csv('modified.csv', index=False)